export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CONTACTS_LOADING = "CONTACTS_LOADING";
export const CONTACTS_LOADING_SUCCESS = "CONTACTS_LOADING_SUCCESS";
export const CONTACTS_LOADING_ERROR = "CONTACTS_LOADING_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";

export const ADD_CONTACT_LOADING = "ADD_CONTACT_LOADING";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";
export const CLEAR_ADD_CONTACT = "CLEAR_ADD_CONTACT";

export const SEARCH_CONTACTS = "SEARCH_CONTACTS";

export const DELETE_CONTACT_LOADING = "DELETE_CONTACT_LOADING";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";

export const STAR_UNSTAR_LOADING = "STAR_UNSTAR_LOADING";
export const STAR_UNSTAR_SUCCESS = "STAR_UNSTAR_SUCCESS";
export const STAR_UNSTAR_ERROR = "STAR_UNSTAR_ERROR";